const data = {
  id: 1,
  name: "Earth (C-137)",
  type: "Planet",
  residents: [
    {
      id: 394,
      name: "Davin",
      status: "Dead",
      image: "https://rickandmortyapi.com/api/character/avatar/394.jpeg",
    },
    {
      id: 356,
      name: "Tom Randolph",
      status: "Alive",
      image: "https://rickandmortyapi.com/api/character/avatar/356.jpeg",
    },
    {
      id: 343,
      name: "Tammy Guetermann",
      status: "Alive",
      image: "https://rickandmortyapi.com/api/character/avatar/343.jpeg",
    },
    {
      id: 338,
      name: "Summer Smith",
      status: "Alive",
      image: "https://rickandmortyapi.com/api/character/avatar/338.jpeg",
    },
    {
      id: 303,
      name: "Samantha",
      status: "Alive",
      image: "https://rickandmortyapi.com/api/character/avatar/303.jpeg",
    },
    {
      id: 302,
      name: "Ruben",
      status: "Dead",
      image: "https://rickandmortyapi.com/api/character/avatar/302.jpeg",
    },
    {
      id: 271,
      name: "Principal Vagina",
      status: "Alive",
      image: "https://rickandmortyapi.com/api/character/avatar/271.jpeg",
    },
    {
      id: 239,
      name: "Mr. Goldenfold",
      status: "Alive",
      image: "https://rickandmortyapi.com/api/character/avatar/239.jpeg",
    },
    {
      id: 216,
      name: "MC Haps",
      status: "Alive",
      image: "https://rickandmortyapi.com/api/character/avatar/216.jpeg",
    },
    {
      id: 201,
      name: "Leonard Smith",
      status: "Alive",
      image: "https://rickandmortyapi.com/api/character/avatar/201.jpeg",
    },
    {
      id: 186,
      name: "Joyce Smith",
      status: "Alive",
      image: "https://rickandmortyapi.com/api/character/avatar/186.jpeg",
    },
    {
      id: 179,
      name: "Jessica",
      status: "Alive",
      image: "https://rickandmortyapi.com/api/character/avatar/179.jpeg",
    },
    {
      id: 175,
      name: "Jerry Smith",
      status: "Alive",
      image: "https://rickandmortyapi.com/api/character/avatar/175.jpeg",
    },
    {
      id: 169,
      name: "Jacob",
      status: "Alive",
      image: "https://rickandmortyapi.com/api/character/avatar/169.jpeg",
    },
    {
      id: 155,
      name: "Harold",
      status: "Alive",
      image: "https://rickandmortyapi.com/api/character/avatar/155.jpeg",
    },
    {
      id: 127,
      name: "Frank Palicky",
      status: "Dead",
      image: "https://rickandmortyapi.com/api/character/avatar/127.jpeg",
    },
    {
      id: 120,
      name: "Evil Summer Clone",
      status: "Dead",
      image: "https://rickandmortyapi.com/api/character/avatar/120.jpeg",
    },
    {
      id: 117,
      name: "Evil Jerry Clone",
      status: "Dead",
      image: "https://rickandmortyapi.com/api/character/avatar/117.jpeg",
    },
    {
      id: 116,
      name: "Evil Beth Clone",
      status: "Dead",
      image: "https://rickandmortyapi.com/api/character/avatar/116.jpeg",
    },
    {
      id: 114,
      name: "Ethan",
      status: "unknown",
      image: "https://rickandmortyapi.com/api/character/avatar/114.jpeg",
    },
    {
      id: 112,
      name: "Eric McMan",
      status: "Alive",
      image: "https://rickandmortyapi.com/api/character/avatar/112.jpeg",
    },
    {
      id: 92,
      name: "Davin",
      status: "Dead",
      image: "https://rickandmortyapi.com/api/character/avatar/92.jpeg",
    },
    {
      id: 83,
      name: "Cronenberg Morty",
      status: "unknown",
      image: "https://rickandmortyapi.com/api/character/avatar/83.jpeg",
    },
    {
      id: 82,
      name: "Cronenberg Rick",
      status: "unknown",
      image: "https://rickandmortyapi.com/api/character/avatar/82.jpeg",
    },
    {
      id: 71,
      name: "Conroy",
      status: "Dead",
      image: "https://rickandmortyapi.com/api/character/avatar/71.jpeg",
    },
    {
      id: 45,
      name: "Bill",
      status: "Alive",
      image: "https://rickandmortyapi.com/api/character/avatar/45.jpeg",
    },
    {
      id: 38,
      name: "Beth Smith",
      status: "Alive",
      image: "https://rickandmortyapi.com/api/character/avatar/38.jpeg",
    },
  ],
};
export default data;
